### ISSUE TITLE
"faker" TypeError: faker.integer is not a function

### ISSUE THREAD

**Issue by sophieyoung717** [danibram/mocker-data-generator#5]
var mocker=require("mocker-data-generator");
var util=require("util");

var Product = {
    brand: {
        values: ['Apple','Samsung','Sony']
    },
    category: {
        values: ['laptop','phone','TV']
    },
    price: {
        faker: 'integer({"min": 300, "max": 3000})'
    },
    number: {
        faker: 'integer({"min": 0, "max": 100})'
    },
    discount: {
        faker: 'double({"min": 0, "max": 0.9})'
    }
};

mocker()
    .schema('Product', Product, 10)
    .build(function(data) {
        console.log(util.inspect(data, { depth: 10 }))
//This returns an object
// {
//      user:[array of users],
//      group: [array of groups],
//      conditionalField: [array of conditionalFields]
// }
    })

The error message is: 
/usr/local/bin/node DataGenerator.js
Error:  Schema: "Product" Generator: "faker" TypeError: faker.integer is not a function
    at /Users/yingyang/Documents/JavaScript/DataCleaning/node_modules/mocker-data-generator/lib/Mocker.js:58:35
    at Array.reduce (native)
    at Mocker.build (/Users/yingyang/Documents/JavaScript/DataCleaning/node_modules/mocker-data-generator/lib/Mocker.js:52:26)
    at Object.<anonymous> (/Users/yingyang/Documents/JavaScript/DataCleaning/DataGenerator.js:28:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
{ Product: undefined }

**Comment by danibram** [comment]
check https://github.com/marak/Faker.js/ documentation i think the you must replace integer and double by random.number. Integer and double not exists on fakerJs
